package model.dto;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class FootTrafficMdtDTO {
	private String year;
	private String quarter;
	private String level2Name;
	private double mA10MonT1FtCnt;
	private double mA10MonT2FtCnt;
	private double mA10MonT3FtCnt;
	private double mA10MonT4FtCnt;
	private double mA10MonT5FtCnt;
	private double mA10MonT6FtCnt;
	private double mA10TueT1FtCnt;
	private double mA10TueT2FtCnt;
	private double mA10TueT3FtCnt;
	private double mA10TueT4FtCnt;
	private double mA10TueT5FtCnt;
	private double mA10TueT6FtCnt;
	private double mA10WedT1FtCnt;
	private double mA10WedT2FtCnt;
	private double mA10WedT3FtCnt;
	private double mA10WedT4FtCnt;
	private double mA10WedT5FtCnt;
	private double mA10WedT6FtCnt;
	private double mA10ThuT1FtCnt;
	private double mA10ThuT2FtCnt;
	private double mA10ThuT3FtCnt;
	private double mA10ThuT4FtCnt;
	private double mA10ThuT5FtCnt;
	private double mA10ThuT6FtCnt;
	private double mA10FriT1FtCnt;
	private double mA10FriT2FtCnt;
	private double mA10FriT3FtCnt;
	private double mA10FriT4FtCnt;
	private double mA10FriT5FtCnt;
	private double mA10FriT6FtCnt;
	private double mA10SatT1FtCnt;
	private double mA10SatT2FtCnt;
	private double mA10SatT3FtCnt;
	private double mA10SatT4FtCnt;
	private double mA10SatT5FtCnt;
	private double mA10SatT6FtCnt;
	private double mA10SunT1FtCnt;
	private double mA10SunT2FtCnt;
	private double mA10SunT3FtCnt;
	private double mA10SunT4FtCnt;
	private double mA10SunT5FtCnt;
	private double mA10SunT6FtCnt;
	private double mA20MonT1FtCnt;
	private double mA20MonT2FtCnt;
	private double mA20MonT3FtCnt;
	private double mA20MonT4FtCnt;
	private double mA20MonT5FtCnt;
	private double mA20MonT6FtCnt;
	private double mA20TueT1FtCnt;
	private double mA20TueT2FtCnt;
	private double mA20TueT3FtCnt;
	private double mA20TueT4FtCnt;
	private double mA20TueT5FtCnt;
	private double mA20TueT6FtCnt;
	private double mA20WedT1FtCnt;
	private double mA20WedT2FtCnt;
	private double mA20WedT3FtCnt;
	private double mA20WedT4FtCnt;
	private double mA20WedT5FtCnt;
	private double mA20WedT6FtCnt;
	private double mA20ThuT1FtCnt;
	private double mA20ThuT2FtCnt;
	private double mA20ThuT3FtCnt;
	private double mA20ThuT4FtCnt;
	private double mA20ThuT5FtCnt;
	private double mA20ThuT6FtCnt;
	private double mA20FriT1FtCnt;
	private double mA20FriT2FtCnt;
	private double mA20FriT3FtCnt;
	private double mA20FriT4FtCnt;
	private double mA20FriT5FtCnt;
	private double mA20FriT6FtCnt;
	private double mA20SatT1FtCnt;
	private double mA20SatT2FtCnt;
	private double mA20SatT3FtCnt;
	private double mA20SatT4FtCnt;
	private double mA20SatT5FtCnt;
	private double mA20SatT6FtCnt;
	private double mA20SunT1FtCnt;
	private double mA20SunT2FtCnt;
	private double mA20SunT3FtCnt;
	private double mA20SunT4FtCnt;
	private double mA20SunT5FtCnt;
	private double mA20SunT6FtCnt;
	private double mA30MonT1FtCnt;
	private double mA30MonT2FtCnt;
	private double mA30MonT3FtCnt;
	private double mA30MonT4FtCnt;
	private double mA30MonT5FtCnt;
	private double mA30MonT6FtCnt;
	private double mA30TueT1FtCnt;
	private double mA30TueT2FtCnt;
	private double mA30TueT3FtCnt;
	private double mA30TueT4FtCnt;
	private double mA30TueT5FtCnt;
	private double mA30TueT6FtCnt;
	private double mA30WedT1FtCnt;
	private double mA30WedT2FtCnt;
	private double mA30WedT3FtCnt;
	private double mA30WedT4FtCnt;
	private double mA30WedT5FtCnt;
	private double mA30WedT6FtCnt;
	private double mA30ThuT1FtCnt;
	private double mA30ThuT2FtCnt;
	private double mA30ThuT3FtCnt;
	private double mA30ThuT4FtCnt;
	private double mA30ThuT5FtCnt;
	private double mA30ThuT6FtCnt;
	private double mA30FriT1FtCnt;
	private double mA30FriT2FtCnt;
	private double mA30FriT3FtCnt;
	private double mA30FriT4FtCnt;
	private double mA30FriT5FtCnt;
	private double mA30FriT6FtCnt;
	private double mA30SatT1FtCnt;
	private double mA30SatT2FtCnt;
	private double mA30SatT3FtCnt;
	private double mA30SatT4FtCnt;
	private double mA30SatT5FtCnt;
	private double mA30SatT6FtCnt;
	private double mA30SunT1FtCnt;
	private double mA30SunT2FtCnt;
	private double mA30SunT3FtCnt;
	private double mA30SunT4FtCnt;
	priva

	



}
